In [52]:
import pandas as pd
import plotly.express as px
from sklearn.metrics import silhouette_score, silhouette_samples
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster,cophenet
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

### Estandarización y selección de columnas para cluster de productos

In [41]:
#Leyendo el dataset
resumen_productos = pd.read_csv('../data_clean/resumen_productos.csv')
resumen_productos.head(5)

,ID_Producto,Nombre_producto,Categoría,Precio_Unitario,Stock,Unidades_Vendidas,Venta_Total,Transacciones,%_Unidades,%_Venta,Cancelada,Completa,Pendiente
0,6,Asado,Carnicería,28.56,5137,299,8539.44,81,2.863710,8.282421,0,71,10
1,8,Milanesa,Carnicería,16.21,3140,320,5187.20,89,3.064841,5.031076,0,76,13
2,25,Pizza congelada,Congelados,15.45,1640,332,5129.40,86,3.179772,4.975016,1,79,6
3,4,Queso rallado,Lácteos,19.23,2099,259,4980.57,77,2.480605,4.830665,1,67,9
4,3,Queso cremoso,Lácteos,17.23,3167,268,4617.64,84,2.566804,4.478659,0,66,18

In [44]:
resumen_productos['Porc_Canceladas'] = resumen_productos['Cancelada']/resumen_productos['Transacciones'] *100
resumen_productos['Porc_Completadas'] = resumen_productos['Completa']/resumen_productos['Transacciones'] *100
resumen_productos['Porc_Pendientes'] = resumen_productos['Pendiente']/resumen_productos['Transacciones'] *100


resumen_productos['Porc_Unidades'] = resumen_productos['%_Unidades']/100
resumen_productos['Porc_Ventas'] = resumen_productos['%_Venta']/100

In [46]:
resumen_productos = resumen_productos.drop(columns=['Cancelada', 'Completa', 'Pendiente', '%_Unidades', '%_Venta'])

resumen_productos.head(5)

,ID_Producto,Nombre_producto,Categoría,Precio_Unitario,Stock,Unidades_Vendidas,Venta_Total,Transacciones,Porc_Canceladas,Porc_Completadas,Porc_Pendientes,Porc_Unidades,Porc_Ventas
0,6,Asado,Carnicería,28.56,5137,299,8539.44,81,0.000000,87.654321,12.345679,0.028637,0.082824
1,8,Milanesa,Carnicería,16.21,3140,320,5187.20,89,0.000000,85.393258,14.606742,0.030648,0.050311
2,25,Pizza congelada,Congelados,15.45,1640,332,5129.40,86,1.162791,91.860465,6.976744,0.031798,0.049750
3,4,Queso rallado,Lácteos,19.23,2099,259,4980.57,77,1.298701,87.012987,11.688312,0.024806,0.048307
4,3,Queso cremoso,Lácteos,17.23,3167,268,4617.64,84,0.000000,78.571429,21.428571,0.025668,0.044787

In [48]:
#Filtrando las posibles columnas a usar
interest_cols = ['Categoría', 'Unidades_Vendidas', 'Venta_Total', 'Transacciones', 'Porc_Unidades', 'Porc_Ventas', 'Precio_Unitario', 'Porc_Canceladas', 'Porc_Completadas', 'Porc_Pendientes', 'Stock']
X_prod = resumen_productos[interest_cols]
X_prod = X_prod.rename(columns={'Categoría': 'Categoria'})
X_prod.head(5)

,Categoria,Unidades_Vendidas,Venta_Total,Transacciones,Porc_Unidades,Porc_Ventas,Precio_Unitario,Porc_Canceladas,Porc_Completadas,Porc_Pendientes,Stock
0,Carnicería,299,8539.44,81,0.028637,0.082824,28.56,0.000000,87.654321,12.345679,5137
1,Carnicería,320,5187.20,89,0.030648,0.050311,16.21,0.000000,85.393258,14.606742,3140
2,Congelados,332,5129.40,86,0.031798,0.049750,15.45,1.162791,91.860465,6.976744,1640
3,Lácteos,259,4980.57,77,0.024806,0.048307,19.23,1.298701,87.012987,11.688312,2099
4,Lácteos,268,4617.64,84,0.025668,0.044787,17.23,0.000000,78.571429,21.428571,3167

In [63]:
#Aplicando OneHotEncoder a categoria 

X_prod = pd.get_dummies(X_prod, drop_first=True, dtype=int)

In [64]:
X_prod

,Unidades_Vendidas,Venta_Total,Transacciones,Porc_Unidades,Porc_Ventas,Precio_Unitario,Porc_Canceladas,Porc_Completadas,Porc_Pendientes,Stock,Categoria_Carnicería,Categoria_Congelados,Categoria_Conservas,Categoria_Frutas y Verduras,Categoria_Galletitas y Snacks,Categoria_Lácteos,Categoria_Panadería
0,299.0,8539.44,81.0,0.028637,0.082824,28.56,0.000000,87.654321,12.345679,5137.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,320.0,5187.20,89.0,0.030648,0.050311,16.21,0.000000,85.393258,14.606742,3140.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,332.0,5129.40,86.0,0.031798,0.049750,15.45,1.162791,91.860465,6.976744,1640.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,259.0,4980.57,77.0,0.024806,0.048307,19.23,1.298701,87.012987,11.688312,2099.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,268.0,4617.64,84.0,0.025668,0.044787,17.23,0.000000,78.571429,21.428571,3167.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,246.0,4565.76,71.0,0.023561,0.044283,18.56,0.000000,85.915493,14.084507,4051.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,350.0,4039.00,98.0,0.033522,0.039174,11.54,0.000000,89.795918,10.204082,2455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,277.0,3750.58,75.0,0.026530,0.036377,13.54,0.000000,85.333333,14.666667,2908.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,375.0,3577.50,105.0,0.035916,0.034698,9.54,0.000000,81.904762,18.095238,1688.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,250.0,3562.50,68.0,0.023944,0.034553,14.25,1.470588,77.941176,20.588235,2429.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10,229.0,3487.67,69.0,0.021933,0.033827,15.23,4.347826,82.608696,13.043478,3189.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,276.0,3378.24,81.0,0.026434,0.032766,12.24,0.000000,85.185185,14.814815,3327.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,241.0,3263.14,76.0,0.023082,0.031649,13.54,0.000000,85.526316,14.473684,1363.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,286.0,3217.50,71.0,0.027392,0.031207,11.25,0.000000,81.690141,18.309859,4068.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14,256.0,3215.36,73.0,0.024519,0.031186,12.56,0.000000,89.041096,10.958904,2228.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,254.0,2852.42,73.0,0.024327,0.027666,11.23,0.000000,80.821918,19.178082,1726.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,216.0,2669.76,70.0,0.020688,0.025894,12.36,0.000000,88.571429,11.428571,3125.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,299.0,2460.77,92.0,0.028637,0.023867,8.23,0.000000,77.173913,22.826087,3731.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18,293.0,2379.16,82.0,0.028062,0.023076,8.12,0.000000,82.926829,17.073171,1619.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,357.0,2216.97,93.0,0.034192,0.021502,6.21,0.000000,91.397849,8.602151,4978.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,228.0,2154.60,72.0,0.021837,0.020898,9.45,0.000000,80.555556,19.444444,3637.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,332.0,2075.00,91.0,0.031798,0.020125,6.25,0.000000,83.516484,16.483516,5057.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
22,229.0,1955.66,72.0,0.021933,0.018968,8.54,0.000000,88.888889,11.111111,2837.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23,313.0,1943.73,83.0,0.029978,0.018852,6.21,0.000000,86.746988,13.253012,2182.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,297.0,1942.38,88.0,0.028446,0.018839,6.54,0.000000,84.090909,15.909091,3383.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
25,300.0,1695.00,80.0,0.028733,0.016440,5.65,1.250000,81.250000,17.500000,4929.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
26,239.0,1563.06,75.0,0.022891,0.015160,6.54,0.000000,73.333333,26.666667,4041.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,298.0,1561.52,87.0,0.028541,0.015145,5.24,1.149425,73.563218,25.287356,2771.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28,214.0,1551.50,65.0,0.020496,0.015048,7.25,0.000000,84.615385,15.384615,4720.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29,282.0,1536.90,73.0,0.027009,0.014906,5.45,0.000000,91.780822,8.219178,4769.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
30,273.0,1422.33,82.0,0.026147,0.013795,5.21,1.219512,78.048780,20.731707,3358.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
31,303.0,1287.75,88.0,0.029020,0.012490,4.25,0.000000,84.090909,15.909091,1437.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
32,225.0,956.25,68.0,0.021550,0.009275,4.25,0.000000,89.705882,10.294118,1541.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
33,224.0,943.04,71.0,0.021454,0.009147,4.21,1.408451,78.873239,19.718310,3545.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
34,255.0,930.75,77.0,0.024423,0.009027,3.65,0.000000,84.415584,15.584416,1506.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
35,264.0,926.64,75.0,0.025285,0.008988,3.51,0.000000,88.000000,12.000000,4043.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36,266.0,864.50,78.0,0.025476,0.008385,3.25,0.000000,85.897436,14.102564,2800.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
37,216.0,702.00,61.0,0.020688,0.006809,3.25,0.000000,81.967213,18.032787,4578.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [66]:
# Aplicando el StandardScaler a los datos 
scaler = StandardScaler()
X_scaled_values = scaler.fit_transform(X_prod)
X_prod_scaled = pd.DataFrame(X_scaled_values, columns=X_prod.columns)

X_prod_scaled.head(5)

,Unidades_Vendidas,Venta_Total,Transacciones,Porc_Unidades,Porc_Ventas,Precio_Unitario,Porc_Canceladas,Porc_Completadas,Porc_Pendientes,Stock,Categoria_Carnicería,Categoria_Congelados,Categoria_Conservas,Categoria_Frutas y Verduras,Categoria_Galletitas y Snacks,Categoria_Lácteos,Categoria_Panadería
0,0.589461,3.640095,0.217133,0.589461,3.640095,3.392403,-0.425004,0.766728,-0.708987,1.746380,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
1,1.100200,1.545681,1.063395,1.100200,1.545681,1.154800,-0.425004,0.279457,-0.209220,0.002711,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
2,1.392051,1.509568,0.746046,1.392051,1.509568,1.017101,0.986195,1.673173,-1.895691,-1.307005,-0.433013,2.915476,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
3,-0.383374,1.416582,-0.205998,-0.383374,1.416582,1.701971,1.151140,0.628517,-0.854286,-0.906232,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
4,-0.164486,1.189831,0.534481,-0.164486,1.189831,1.339606,-0.425004,-1.190681,1.298620,0.026286,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249

In [69]:
correlation =  X_prod.corr()

fig = px.imshow(correlation, text_auto=".2f")
fig.update_layout(width = 1200, height = 1200)
fig.show()

Como se puede observar hay diversas variables que tienen una alta correlación entre si lo cuál no es adecuado para lograr hacer clustering, debido a ello se utilizarán únicamente las columnas: 

- Porc_Completadas
- Porc_Canceladas
- Precio_Unitario
- Stock
- Unidades_Vendidas
- Todas las categorías

In [72]:
not_used_cols = ['Venta_Total', 'Transacciones', 'Porc_Unidades', 'Porc_Ventas', 'Porc_Pendientes']

X_prod_scaled = X_prod_scaled.drop(columns=not_used_cols)

X_prod_scaled

,Unidades_Vendidas,Precio_Unitario,Porc_Canceladas,Porc_Completadas,Stock,Categoria_Carnicería,Categoria_Congelados,Categoria_Conservas,Categoria_Frutas y Verduras,Categoria_Galletitas y Snacks,Categoria_Lácteos,Categoria_Panadería
0,0.589461,3.392403,-0.425004,0.766728,1.746380,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
1,1.100200,1.154800,-0.425004,0.279457,0.002711,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
2,1.392051,1.017101,0.986195,1.673173,-1.307005,-0.433013,2.915476,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
3,-0.383374,1.701971,1.151140,0.628517,-0.906232,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
4,-0.164486,1.339606,-0.425004,-1.190681,0.026286,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
5,-0.699545,1.580579,-0.425004,0.392001,0.798146,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
6,1.829826,0.308678,-0.425004,1.228253,-0.595392,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
7,0.054402,0.671043,-0.425004,0.266543,-0.199858,-0.433013,2.915476,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
8,2.437848,-0.053687,-0.425004,-0.472331,-1.265094,-0.433013,2.915476,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
9,-0.602262,0.799682,1.359748,-1.326504,-0.618094,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
10,-1.113000,0.977241,4.851652,-0.320630,0.045495,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,2.569047
11,0.030081,0.435505,-0.425004,0.234616,0.165989,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
12,-0.821150,0.671043,-0.425004,0.308132,-1.548866,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
13,0.273290,0.256135,-0.425004,-0.518583,0.812989,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
14,-0.456337,0.493484,-0.425004,1.065584,-0.793596,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,2.569047
15,-0.504978,0.252511,-0.425004,-0.705690,-1.231914,2.309401,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
16,-1.429172,0.457247,-0.425004,0.964369,-0.010386,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,2.569047
17,0.589461,-0.291036,-0.425004,-1.491853,0.518739,-0.433013,2.915476,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
18,0.443536,-0.310966,-0.425004,-0.252071,-1.325341,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,2.569047
19,2.000073,-0.657025,-0.425004,1.573477,1.607550,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
20,-1.137321,-0.069994,-0.425004,-0.763092,0.436664,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,-0.389249
21,1.392051,-0.649778,-0.425004,-0.124997,1.676529,-0.433013,-0.342997,-0.342997,-0.433013,2.915476,-0.389249,-0.389249
22,-1.113000,-0.234870,-0.425004,1.032783,-0.261851,-0.433013,-0.342997,-0.342997,-0.433013,2.915476,-0.389249,-0.389249
23,0.929954,-0.657025,-0.425004,0.571193,-0.833761,-0.433013,-0.342997,2.915476,-0.433013,-0.342997,-0.389249,-0.389249
24,0.540820,-0.597235,-0.425004,-0.001206,0.214885,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
25,0.613782,-0.758487,1.092035,-0.613436,1.564766,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
26,-0.869792,-0.597235,-0.425004,-2.319517,0.789414,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
27,0.565141,-0.832772,0.969974,-2.269976,-0.319479,-0.433013,-0.342997,-0.342997,-0.433013,2.915476,-0.389249,-0.389249
28,-1.477814,-0.468595,-0.425004,0.111821,1.382279,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
29,0.176006,-0.794724,-0.425004,1.656009,1.425063,-0.433013,-0.342997,-0.342997,-0.433013,2.915476,-0.389249,-0.389249
30,-0.042882,-0.838207,1.055034,-1.303315,0.193057,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,2.569047,-0.389249
31,0.686745,-1.012142,-0.425004,-0.001206,-1.484253,-0.433013,-0.342997,2.915476,-0.433013,-0.342997,-0.389249,-0.389249
32,-1.210284,-1.012142,-0.425004,1.208849,-1.393446,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
33,-1.234605,-1.019390,1.284336,-1.125640,0.356335,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
34,-0.480657,-1.120852,-0.425004,0.068763,-1.424006,-0.433013,-0.342997,2.915476,-0.433013,-0.342997,-0.389249,-0.389249
35,-0.261770,-1.146217,-0.425004,0.841223,0.791160,-0.433013,-0.342997,-0.342997,-0.433013,-0.342997,-0.389249,2.569047
36,-0.213128,-1.193325,-0.425004,0.388110,-0.294158,-0.433013,-0.342997,-0.342997,2.309401,-0.342997,-0.389249,-0.389249
37,-1.429172,-1.193325,-0.425004,-0.458873,1.258293,-0.433013,-0.342997,2.915476,-0.433013,-0.342997,-0.389249,-0.389249